import { useEffect, useMemo, useState } from 'react';
import { Alert, Spin } from 'antd';
import { ArrowRightOutlined, BoxPlotOutlined, CalendarOutlined, ExclamationCircleFilled, FileTextOutlined, FundOutlined, InboxOutlined, RiseOutlined, ShoppingCartOutlined } from '@ant-design/icons';
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import dayjs, { Dayjs } from 'dayjs';
import { useAuth } from '../contexts/AuthContext';
import maskPouch from '../assets/unbranded-mask-pouch.webp';
import looseMasks from '../assets/neutral-loose-pouch.webp';
import sealedCarton from '../assets/warehouse-sack-sealed.webp';
import openedCarton from '../assets/warehouse-sack-opened.webp';
import { isVietnamRestDay } from '../lib/workCalendar';
import './Dashboard.css';

type Product = { name: string; qty: number; revenue: number };
type Purchase = { id: number; supplierName?: string; totalAmount: number; purchaseDate: string; createdAt: string };
type Summary = { revenue:number; prevRevenue:number; orderCount:number; prevOrders:number; posRevenue:number; posCount:number; ecomRevenue:number; ecomCount:number; grossProfit:number; totalStock:number; productCount:number; lowStockCount:number; purchaseCount:number; purchases:Purchase[]; recentPurchases:Purchase[]; dailyRevenueByDate:Record<string,number>; topProducts:Product[] };
const none: Summary = { revenue:0,prevRevenue:0,orderCount:0,prevOrders:0,posRevenue:0,posCount:0,ecomRevenue:0,ecomCount:0,grossProfit:0,totalStock:0,productCount:0,lowStockCount:0,purchaseCount:0,purchases:[],recentPurchases:[],dailyRevenueByDate:{},topProducts:[] };
const money=(n:number)=>n.toLocaleString('vi-VN');
const compact=(n:number)=>Math.abs(n)>=1e9?`${(n/1e9).toFixed(1).replace(/\.0$/,'')}tỷ`:Math.abs(n)>=1e6?`${(n/1e6).toFixed(1).replace(/\.0$/,'')}tr`:Math.abs(n)>=1e3?`${Math.round(n/1e3)}k`:`${n}`;
const delta=(now:number,before:number)=>before===0?(now===0?null:100):+(((now-before)/before)*100).toFixed(1);
const images=[maskPouch,looseMasks,sealedCarton,maskPouch,openedCarton];
const DASHBOARD_CACHE_MAX_AGE_MS=24*60*60*1000;
function readSummaryCache(key:string){try{const raw=localStorage.getItem(key);if(!raw)return null;const cached=JSON.parse(raw) as {savedAt:number;data:Summary};if(!cached?.savedAt||Date.now()-cached.savedAt>DASHBOARD_CACHE_MAX_AGE_MS){localStorage.removeItem(key);return null;}return cached.data;}catch{return null;}}
function writeSummaryCache(key:string,data:Summary){try{localStorage.setItem(key,JSON.stringify({savedAt:Date.now(),data}));}catch{}}
function range(key:string,today:Dayjs){const pair=(from:Dayjs,to:Dayjs,prevFrom:Dayjs,prevTo:Dayjs)=>({from,to,prevFrom,prevTo});if(key==='today')return pair(today.startOf('day'),today.endOf('day'),today.subtract(1,'day').startOf('day'),today.subtract(1,'day').endOf('day'));if(key==='7days')return pair(today.subtract(6,'day').startOf('day'),today.endOf('day'),today.subtract(13,'day').startOf('day'),today.subtract(7,'day').endOf('day'));if(key==='30days')return pair(today.subtract(29,'day').startOf('day'),today.endOf('day'),today.subtract(59,'day').startOf('day'),today.subtract(30,'day').endOf('day'));return pair(today.startOf('month'),today.endOf('day'),today.subtract(1,'month').startOf('month'),today.subtract(1,'month').endOf('month'));}

export default function DashboardPage(){
 const {user}=useAuth();const [period,setPeriod]=useState('7days');const [summary,setSummary]=useState<Summary>(none);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const today=dayjs().startOf('day');const selectedRange=useMemo(()=>range(period,today),[period,today.valueOf()]);
 const chartDates=useMemo(()=>{const count=Math.max(selectedRange.to.diff(selectedRange.from,'day')+1,1);return Array.from({length:count},(_,i)=>selectedRange.from.add(i,'day')).filter(date=>!date.isAfter(today,'day')&&!isVietnamRestDay(date));},[selectedRange,today.valueOf()]);
 useEffect(()=>{document.querySelector<HTMLElement>('.ant-layout-content')?.scrollTo({top:0});},[]);
 useEffect(()=>{if(user?.role!=='admin')return;let stopped=false;const cacheKey=`dashboard-summary-v3:${user.id}:${period}:${selectedRange.from.format('YYYY-MM-DD')}`;const cached=readSummaryCache(cacheKey);if(cached)setSummary({...none,...cached});else setSummary(none);const load=async()=>{setLoading(true);setError('');try{const result=await window.electronAPI.dashboard.getSummary({from:selectedRange.from.toISOString(),to:selectedRange.to.toISOString(),prevFrom:selectedRange.prevFrom.toISOString(),prevTo:selectedRange.prevTo.toISOString(),chartFrom:selectedRange.from.startOf('day').toISOString(),chartTo:selectedRange.to.endOf('day').toISOString()});if(!stopped){if(result.success&&result.data){const next={...none,...result.data};setSummary(next);writeSummaryCache(cacheKey,next);}else{if(!cached)setSummary(none);setError(result.error||'Không tải được dữ liệu tổng quan');}}}catch(reason){if(!stopped){if(!cached)setSummary(none);setError(reason instanceof Error?reason.message:String(reason));}}finally{if(!stopped)setLoading(false);}};void load();return()=>{stopped=true;};},[user?.id,user?.role,period,selectedRange]);
 const chart=chartDates.map(d=>({date:d.format('DD/MM'),revenue:summary.dailyRevenueByDate[d.format('YYYY-MM-DD')]||0})).filter(point=>point.revenue>0);const chartTitle=period==='today'?'Doanh thu hôm nay':period==='7days'?'Doanh thu 7 ngày':period==='30days'?'Doanh thu 30 ngày':'Doanh thu tháng này';const products=summary.topProducts.slice(0,5);const maxQty=Math.max(...products.map(p=>p.qty),1);const channelTotal=summary.posRevenue+summary.ecomRevenue;const channels=[{name:'POS tại quầy',value:summary.posRevenue,color:'#00ab56'},{name:'Sàn TMĐT',value:summary.ecomRevenue,color:'#2f6fed'}];const latest=(summary.purchaseCount?summary.purchases:summary.recentPurchases)[0];
 if(user?.role!=='admin')return <div className="dashboard-empty"><ExclamationCircleFilled/><strong>Không có quyền truy cập</strong><span>Chỉ tài khoản Admin mới được xem trang Tổng quan.</span></div>;if(loading&&summary===none)return <div className="dashboard-loader"><Spin size="large"/></div>;
 return <main className="dashboard-v2">{error&&<Alert type="warning" showIcon message={error} className="dashboard-alert"/>}<header className="dashboard-v2__header"><div><p>TRUNG TÂM ĐIỀU HÀNH</p><h1>Tổng quan</h1><span>Cập nhật theo dữ liệu bán hàng mới nhất</span></div><div className="dashboard-v2__date-controls" aria-label="Chọn khoảng thời gian"><div className="dashboard-v2__periods">{[{key:'today',label:'Hôm nay'},{key:'7days',label:'7 ngày'},{key:'30days',label:'30 ngày'},{key:'month',label:'Tháng này'}].map(item=><button type="button" key={item.key} className={period===item.key?'is-active':''} onClick={()=>setPeriod(item.key)}>{item.label}</button>)}</div><div className="dashboard-v2__date-range"><CalendarOutlined/><span>{selectedRange.from.format('DD/MM/YYYY')} – {selectedRange.to.format('DD/MM/YYYY')}</span></div></div></header>
 <section className="dashboard-v2__pulse"><Pulse icon={<FundOutlined/>} label="Doanh thu" value={`${compact(summary.revenue)}đ`} change={delta(summary.revenue,summary.prevRevenue)}/><Pulse icon={<ShoppingCartOutlined/>} label="Đơn hàng" value={`${summary.orderCount}`} change={delta(summary.orderCount,summary.prevOrders)}/><Pulse icon={<BoxPlotOutlined/>} label="Tồn kho sắp hết" value={`${summary.lowStockCount}`} tone="warning" note="sản phẩm cần chú ý"/><Pulse icon={<FileTextOutlined/>} label="Hóa đơn cần xử lý" value="4" tone="danger" note="phiếu chưa có HĐ VAT"/></section>
 <section className="dashboard-v2__core"><aside className="dashboard-v2__stat-rail"><Metric icon={<RiseOutlined/>} label="Lợi nhuận gộp" value={`${compact(summary.grossProfit)}đ`} note={`Biên LN: ${summary.revenue?((summary.grossProfit/summary.revenue)*100).toFixed(1):0}%`}/><Metric icon={<InboxOutlined/>} label="Tồn kho" value={money(summary.totalStock)} note={`${summary.productCount} SKU đang quản lý`}/></aside><article className="dashboard-v2__chart-panel"><Heading title={chartTitle} value={`${compact(chart.reduce((a,b)=>a+b.revenue,0))}đ`}/><div className="dashboard-v2__chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{top:20,right:4,left:-20,bottom:0}}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#00ab56" stopOpacity={.25}/><stop offset="1" stopColor="#00ab56" stopOpacity={.01}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e5eee8"/><XAxis dataKey="date" tickLine={false} axisLine={false} tick={{fill:'#718079',fontSize:11}}/><YAxis tickFormatter={v=>`${v/1000000}tr`} tickLine={false} axisLine={false} tick={{fill:'#718079',fontSize:11}}/><Tooltip formatter={(v:number)=>[`${money(v)}đ`,'Doanh thu']} contentStyle={{border:'1px solid #dce9e1',borderRadius:10}}/><Area type="monotone" dataKey="revenue" stroke="#00ab56" strokeWidth={3} fill="url(#revenueFill)" activeDot={{r:5,fill:'#00ab56',stroke:'#fff',strokeWidth:3}}/></AreaChart></ResponsiveContainer></div><small className="dashboard-v2__chart-note">Đã loại ngày doanh thu 0đ, Chủ nhật và ngày nghỉ lễ</small></article><aside className="dashboard-v2__activity"><Heading title="Hoạt động gần đây" action="Xem tất cả"/><Activity icon={<FileTextOutlined/>} tone="danger" title="Tạo phiếu nhập #299" body={latest?.supplierName||'CÔNG TY PHÚC NHI'} value={latest?`${compact(latest.totalAmount)}đ`:'—'}/><Activity icon={<ShoppingCartOutlined/>} tone="success" title="Đơn hàng mới" body={`${summary.orderCount} đơn trong kỳ`} value={`${compact(summary.revenue)}đ`}/><Activity icon={<BoxPlotOutlined/>} tone="warning" title="Tồn kho thấp" body={`${summary.lowStockCount} sản phẩm cần nhập thêm`} value="Xem danh sách"/><Activity icon={<FileTextOutlined/>} tone="danger" title="Hóa đơn cần xử lý" body="Phiếu chưa có hóa đơn VAT" value="Xem chi tiết"/></aside></section>
 <section className="dashboard-v2__bottom"><article className="dashboard-v2__products"><Heading title="Sản phẩm bán chạy" action="Xem tất cả"/>{products.length?products.map((p,i)=><div className="product-row" key={p.name}><b>{i+1}</b><img src={images[i]} alt="Sản phẩm khẩu trang"/><div><strong>{p.name}</strong><span><i style={{width:`${p.qty/maxQty*100}%`}}/></span></div><small>{p.qty}<em>đã bán</em></small><strong className="product-row__value">{compact(p.revenue)}đ</strong></div>):<Empty text="Chưa có sản phẩm bán chạy trong kỳ này"/>}</article><article className="dashboard-v2__channels"><Heading title="Kênh bán hàng" action="Chi tiết"/>{channelTotal?<div className="channel-body"><div className="channel-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={channels} dataKey="value" innerRadius={55} outerRadius={82} paddingAngle={3} stroke="none">{channels.map(c=><Cell key={c.name} fill={c.color}/>)}</Pie><Tooltip formatter={(v:number)=>`${money(v)}đ`}/></PieChart></ResponsiveContainer><strong>{compact(channelTotal)}đ<small>Tổng doanh thu</small></strong></div><div className="channel-list">{channels.map(c=><div key={c.name}><i style={{background:c.color}}/><span>{c.name}</span><strong>{compact(c.value)}đ</strong><small>{Math.round(c.value/channelTotal*100)}%</small></div>)}</div></div>:<Empty text="Chưa có doanh thu theo kênh"/>}</article></section>{loading&&<div className="dashboard-v2__refresh"><Spin size="small"/> Đang cập nhật</div>}</main>;
}
function Heading({title,value,action}:{title:string;value?:string;action?:string}){return <div className="panel-heading"><div><span>{title}</span>{value&&<strong>{value}</strong>}</div>{action&&<button type="button">{action} <ArrowRightOutlined/></button>}</div>}
function Pulse({icon,label,value,change,tone,note}:{icon:React.ReactNode;label:string;value:string;change?:number|null;tone?:'warning'|'danger';note?:string}){const up=change!==undefined&&change!==null&&change>=0;return <div className={`pulse ${tone?`pulse--${tone}`:''}`}><div className="pulse__icon">{icon}</div><div><span>{label}</span><strong>{value}</strong>{change!==undefined?<small className={up?'positive':'negative'}>{change===null?'—':`${up?'▲':'▼'} ${Math.abs(change)}%`} <em>so với kỳ trước</em></small>:<small>{note}</small>}</div></div>}
function Metric({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}){return <div className="mini-metric"><span>{label}{icon}</span><strong>{value}</strong><small>{note}</small><div/></div>}
function Activity({icon,tone,title,body,value}:{icon:React.ReactNode;tone:'success'|'warning'|'danger';title:string;body:string;value:string}){return <div className="activity-row"><div className={`activity-row__icon activity-row__icon--${tone}`}>{icon}</div><div><strong>{title}</strong><span>{body}</span></div><b className={tone==='danger'?'danger-text':''}>{value}</b></div>}
function Empty({text}:{text:string}){return <div className="dashboard-empty-state">{text}</div>}
